
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class bniForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form bniForm
     */
    public bniForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bniBerhasilBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tagihanBNI = new javax.swing.JTextField();

        setTitle("TRANSFER BNI");

        jLabel1.setText("No Rekening : 112233445566778899");

        bniBerhasilBtn.setText("BERHASIL");
        bniBerhasilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniBerhasilBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tagihan         :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tagihanBNI))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(bniBerhasilBtn)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tagihanBNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bniBerhasilBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bniBerhasilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniBerhasilBtnActionPerformed
        try {            
        double tagihan = Double.parseDouble(tagihanBNI.getText()); // Ambil nilai dari tagihanBNI
        bniBerhasilForm ibf = new bniBerhasilForm(tagihan); // Kirim nilai ke bniBerhasilForm
        ibf.setVisible(true);
        this.getDesktopPane().add(ibf);
        this.dispose();
        hasilBNI.setText(String.valueOf(double tagihan));
        } catch (NumberFormatException e) {
        // Menangani kesalahan jika input bukan angka
        JOptionPane.showMessageDialog(this, "Input tidak valid untuk tagihan BNI.");
    }
    }//GEN-LAST:event_bniBerhasilBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bniBerhasilBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tagihanBNI;
    // End of variables declaration//GEN-END:variables
}
