/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class cashForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form cashForm
     */
    public cashForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tunaiTagihan = new javax.swing.JTextField();
        tunaiBayar = new javax.swing.JTextField();
        tunaiBtn = new javax.swing.JButton();
        kembalian = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        hasilKembalian = new javax.swing.JTextField();

        setTitle("PEMBAYARAN TUNAI");

        jLabel4.setText("TOTAL TAGIHAN       Rp.");

        jLabel5.setText("UANG DIBAYARKAN Rp.");

        tunaiTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiTagihanActionPerformed(evt);
            }
        });

        tunaiBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiBayarActionPerformed(evt);
            }
        });

        tunaiBtn.setText("BAYAR");
        tunaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiBtnActionPerformed(evt);
            }
        });

        kembalian.setText("KEMBALIAN               Rp.");

        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        hasilKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tunaiTagihan)
                            .addComponent(tunaiBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(hasilKembalian))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tunaiBtn)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tunaiTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tunaiBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tunaiBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian)
                    .addComponent(hasilKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        orderForm of = new orderForm();
        of.setVisible(true);
        this.getDesktopPane().add(of);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void tunaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiBtnActionPerformed
        try {
        double tagihan = Double.parseDouble(tunaiTagihan.getText());
        double bayar = Double.parseDouble(tunaiBayar.getText());

        // Menghitung kembalian
        double kembalianValue = bayar - tagihan;

        // Menampilkan hasil kembalian
        hasilKembalian.setText(String.valueOf(kembalianValue));
        } catch (NumberFormatException e) {
        // Menangani kesalahan jika input bukan angka
        hasilKembalian.setText("Input tidak valid");
    } 
    }//GEN-LAST:event_tunaiBtnActionPerformed

    private void tunaiTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiTagihanActionPerformed
        
    }//GEN-LAST:event_tunaiTagihanActionPerformed

    private void hasilKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKembalianActionPerformed
        
    }//GEN-LAST:event_hasilKembalianActionPerformed

    private void tunaiBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiBayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField hasilKembalian;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel kembalian;
    private javax.swing.JTextField tunaiBayar;
    private javax.swing.JButton tunaiBtn;
    private javax.swing.JTextField tunaiTagihan;
    // End of variables declaration//GEN-END:variables
}
